auth:
 jid: servicebot@bots.example.com
 password: SomePassw0rd
 resource: hostname
 server: jabber.example.com
 pidfile: servicebot.pid

acls:

 # Allow moderators from hostbots
 - special: hostbotsMUC
   acl:
     - special: muc_moderator
     - muc: hostbots@conference.example.com

 # Allow moderators from hostbots-dev
 - special: hostbotsDevMUC
   acl:
     - special: muc_moderator
     - muc: hostbots-dev@conference.example.com

 # Allow moderators from hostbots-dev or hostbots
 - special: adminMUC
   acl:
     - anyof:
       - special: hostbotsMUC
       - special: hostbotsDevMUC

cmds:

 # Allow version to be run in any muc context
 - cmd: version
   allow:
    - special: muc

include:
 - path: conf/service/room.yaml
 - path: conf/service/cmd_acls.yaml

